
export const HOME_PAGE = "/:teamid"
export const USER_FORM_PAGE = "/:teamid/person_form"
export const OWNER_FORM_PAGE = "/:teamid/owner_form"
export const AREA_FORM_PAGE = "/:teamid/area_form"
export const ASSET_FORM_PAGE = "/:teamid/asset_form"
export const REPORTS_PAGE = "/:teamid/reports"
export const ASSETS_LINK_PAGE = "/:teamid/links"
export const USER_MANAGEMENT_PAGE = "/:teamid/user_management"
export const PROFILE_PAGE = "/:teamid/profile"
