# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: set dev envs
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        echo '
        TERMINUSDB_SERVER=https://cloud-dev.terminusdb.com/
        AUTH0_DOMAIN=signup-dev.terminusdb.com
        AUTH0_CLIENT_ID=s6iYFJzoSedUHGUUaRYCGGWXWEPHkd02
        AUTH0_AUDIENCE=https://terminuscloud/users
        MY_TEAM=CAMSDemo
        DATA_PRODUCT=CAMS' > .env
    - run: npm ci
    - run: npm run build
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/337086880157/locations/global/workloadIdentityPools/cams/providers/github'
        service_account: 'github-actions-deploy@cams-346210.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Upload to gcloud bucket dev
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: gsutil cp -r dist/* "gs://dashboard-dev.climateresilient.world/"
    - name: Upload to gcloud bucket prod
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
      run: gsutil cp -r dist/* "gs://dashboard.climateresilient.world/"
